# .streamlit/secrets.toml

BINANCE_API_KEY = "yBoOGUUUp571JRSzJmE1VFu05WPad25EvqsXIvvOF8ZxH1MB3zUyFhSKmAmbBnx8"
BINANCE_SECRET_KEY = "ZRtcTb7TlMeaXx7K5AVpwIe7FeWP45ih4hk96wcwc05Kkqzbo0Q9saLm3n73q2Y8"
